### ISSUE TITLE
Doesnt work on android default browser

### ISSUE THREAD

**Issue by vinks** [insin/react-maskedinput#2]
On android default browser user can input only first char. Also there problem with mobile chrome with string patterns.

**Comment by nonmanifold** [comment]
just filter older webkits with version <535. And hope for the best

**Comment by nonmanifold** [comment]
#33 should help to fallback

**Comment by iamdustan** [comment]
this should be fixed in 3.3.0

**Comment by jrodl3r** [comment]
Still not working. You can use the Chrome debugger to connect a remote device and then (through the debugger) you can edit the text-box perfectly fine, then shift over to the device and it works like a charm as well. Right up until you clear out the value and try to start typing again from scratch on the device... Bummer.
